struct Cell *cells;
struct Cell *cells2;
unsigned int numxcells;
unsigned int numycells;
void (*scheme)();
void (*schemefinish)();
void (*bounds)();
double T;
double dt;
double dt0;
struct Event *events;
double numevents;
double nextevent;
double hx;
double hy;
double K;
double beta;
long step;
const double pi = 3.14159265345;
