extern struct Cell *cells;
extern struct Cell *cells2;
extern unsigned int numxcells;
extern unsigned int numycells;
extern void (*scheme)();
extern void (*schemefinish)();
extern void (*bounds)();
extern double T;
extern double dt;
extern double dt0;
extern struct Event *events;
extern double numevents;
extern double nextevent;
extern double hx;
extern double hy;
extern double K;
extern double beta;
extern long step;
extern const double pi;
